### ISSUE TITLE
Error when using along with the graphql-cli

### ISSUE THREAD

**Issue by wtrocki** [kamilkisiela/graphql-config#245]
I have tried to investigate problem and it looks like all of my dependencies are hoisted in root, but somehow graphql-config is not 

```
[wtrocki@wtrockigraph generator-example (layered-resolvers ✗)]$ graphql codegen
{ Error: Cannot find module 'globby'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/wtrocki/.nvm/versions/node/v10.15.3/lib/node_modules/graphql-cli/node_modules/graphql-config/index.js:480:105
    at new Promise (<anonymous>)
    at LoadersRegistry.<anonymous> (/Users/wtrocki/.nvm/versions/node/v10.15.3/lib/node_modules/graphql-cli/node_modules/graphql-config/index.js:480:46)

**Comment by wtrocki** [comment]
Side note. I'm using npm instead of yarn

**Comment by ardatan** [comment]
@wtrocki Does this issue persist?

**Comment by wtrocki** [comment]
Resolved. Using npm was never good idea
