### ISSUE TITLE
If json schema contains a byte order mark (BOM), json parsing fails (eg. default AWS AppSync export)

### ISSUE THREAD

**Issue by 0xdevalias** [kamilkisiela/graphql-config#501]
```
SyntaxError: Error while loading rule 'graphql/template-strings': Unexpected token  in JSON at position 0
Occurred while linting /Users/devalias/dev/REDACTED/schema.graphql
    at JSON.parse (<anonymous>)
    at Object.readSchema (/Users/devalias/dev/REDACTED/node_modules/graphql-config/lib/utils.js:141:38)
    at GraphQLProjectConfig.getSchema (/Users/devalias/dev/REDACTED/node_modules/graphql-config/lib/GraphQLProjectConfig.js:75:28)
    at parseOptions (/Users/devalias/dev/REDACTED/node_modules/eslint-plugin-graphql/lib/index.js:252:34)
    at /Users/devalias/dev/REDACTED/node_modules/eslint-plugin-graphql/lib/index.js:122:16
    at _loop (/Users/devalias/dev/REDACTED/node_modules/eslint-plugin-graphql/lib/createRule.js:175:27)
    at createRule (/Users/devalias/dev/REDACTED/node_modules/eslint-plugin-graphql/lib/createRule.js:194:7)
    at Object.create (/Users/devalias/dev/REDACTED/node_modules/eslint-plugin-graphql/lib/index.js:121:41)
    at createRuleListeners (/Users/devalias/dev/REDACTED/node_modules/eslint/lib/linter/linter.js:746:21)
    at /Users/devalias/dev/REDACTED/node_modules/eslint/lib/linter/linter.js:916:31
```

It seems by default, when exporting the `.json` schema from AWS AppSync it is encoded as UTF-8 with a BOM. Opening and re-saving this file as plain UTF-8 is a workaround for this, but it would be nice if it worked regardless.

**Comment by danielrearden** [comment]
@0xdevalias I just tested this using the latest version of `graphql-config` and it works fine. The loader we use from `graphql-tools` strips the BOM already. `eslint-plugin-graphql` has been updated to use v3 already so I would expect this to work just fine now. If you're still having the same issue using the latest version, can you please provide a short reproduction? Otherwise, I'm going to close this issue for now.
